spring.application.name=upsglam-backend
server.port=${SERVER_PORT}

# Configuración de Supabase (Se usará para Storage y para la Base de Datos vía REST)
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}